name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.33.4]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Lint Deno Module
        run: deno fmt --no-semicolons --check
      - name: Build Deno Module
        run: deno run --reload mod.ts
      - name: Build PDF Module
        run: deno run --allow-env --reload pdf/mod.ts
      - name: Build Serve Module
        run: deno run --reload serve/mod.ts
      - name: Build Render Module
        run: deno run --reload render/mod.ts
      - name: Test Deno Module
        run: deno test --allow-none